version: '3.8'

services:
  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mydatabase.sql:/docker-entrypoint-initdb.d/mydatabase.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    networks:
      - app-network

  app:
    build: .
    container_name: web_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql_server
    environment:
      DB_HOST: mysql_server
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydatabase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: